import { redirect } from 'next/navigation';

/** Document decisions are generated by backend resources; the local demo is retired. */
export default function RetiredLocalDocumentDemo() {
  redirect('/departments/finance');
}
